[package]
name = "rusterizer-s"
version = "0.1.0"
edition = "2021"

[profile.profile]
inherits = "release"
debug = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glam = "0.24.2"
minifb = "0.25.0"
stb_image = "0.3.0"